*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/X7R/0.1uF/50V
* Murata P/N :GCM188R71H104KA57
* Property : C = 0.1[uF]
* Data Generated on Aug 1, 2022
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100Hz-6GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 5V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM188R71H104KA57_DC5V_25degC port1 port2
C1 port1 11 9.78e-8
L2 11 12 2.10e-10
R3 12 13 1.25e-2
C4 13 14 1.03e-5
R4 13 14 388
C5 14 15 2.10e-5
R5 14 15 25.6
C6 15 16 1.38e-5
R6 15 16 9.51
C7 16 17 1.13e-5
R7 16 17 1.17
C8 17 18 9.65e-6
R8 17 18 1.44e-1
C9 18 19 8.65e-6
R9 18 19 2.96e-2
C10 19 20 1.22e-5
R10 19 20 6.66e-3
L11 20 21 1.44e-10
R11 20 21 8.80e-2
L12 21 22 1.06e-11
R12 21 22 5.01e-2
C13 22 23 7.02e-7
L13 22 23 1.94e-11
R13 22 23 2.13e-2
C14 23 24 1.55e-7
L14 23 24 4.23e-11
R14 23 24 3.81e-2
C15 24 25 1.89e-11
L15 24 25 3.27e-11
R15 24 25 3.54
C16 25 port2 1.13e-11
L16 25 port2 3.27e-11
R16 25 port2 3.30
R100 port1 11 5.00e+9
.ENDS GCM188R71H104KA57_DC5V_25degC