*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3225M(1210)/X7R/22uF/25V
* Murata P/N :GRM32ER71E226KE15
* Property : C = 22[uF]
* Data Generated on Oct 1, 2020
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100Hz-6GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 4.33V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM32ER71E226KE15_DC4V33_25degC port1 port2
C1 port1 11 1.62e-5
L2 11 12 2.67e-11
R3 12 13 1.62e-3
C4 13 14 4.20e-4
R4 13 14 12.6
C5 14 15 4.91e-4
R5 14 15 1.18
C6 15 16 4.46e-4
R6 15 16 1.33e-1
C7 16 17 3.51e-4
R7 16 17 1.64e-2
C8 17 18 3.63e-4
R8 17 18 2.11e-3
L9 18 19 4.15e-11
R9 18 19 2.84e-2
L10 19 20 4.28e-10
R10 19 20 1.53e-2
C11 20 21 3.19e-5
L11 20 21 1.50e-10
R11 20 21 9.44e-3
C12 21 22 2.07e-5
L12 21 22 9.95e-11
R12 21 22 7.41e-3
C13 22 port2 1.54e-12
L13 22 port2 3.52e-10
R13 22 port2 64.0
R100 port1 11 2.27e+6
.ENDS GRM32ER71E226KE15_DC4V33_25degC